[build]
  publish = "public"
  command =  "hugo"

[context.production.environment]
  HUGO_VERSION = "0.53"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.53"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.53"

[context.deploy-preview]
command =  "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command =  "hugo -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "/*"
  to = "https://www.eventbrite.co.uk/e/dataopticon-tickets-60620116400"

[[redirects]]
  from = "localhost:1313"
  to = "https://www.eventbrite.co.uk/e/dataopticon-tickets-60620116400"